rabbitmq/rabbitmq-cli

- .gitignore
- Makefile
- README.md
- config/config.exs
- erlang.mk
- lib/rabbitmq/cli/config.ex
- lib/rabbitmq/cli/ctl/auto_complete.ex
- lib/rabbitmq/cli/ctl/command_modules.ex
- lib/rabbitmq/cli/ctl/commands/wait_command.ex
- lib/rabbitmq/cli/ctl/helpers.ex
- lib/rabbitmq/cli/ctl/parser.ex
- lib/rabbitmq/cli/formatters/plugins.ex
- lib/rabbitmq/cli/plugins/commands/disable_command.ex
- lib/rabbitmq/cli/plugins/commands/enable_command.ex
- lib/rabbitmq/cli/plugins/commands/list_command.ex
- lib/rabbitmq/cli/plugins/commands/set_command.ex
- lib/rabbitmq/cli/plugins/plugins_helpers.ex
- lib/rabbitmq/cli/printers/std_io.ex
- lib/rabbitmqctl.ex
- mix.exs
- rabbitmq-components.mk
- test/command_modules_test.exs
- test/helpers_test.exs
- test/parser_test.exs
- test/plugins/disable_plugins_command_test.exs
- test/plugins/enable_plugins_command_test.exs
- test/plugins/list_plugins_command_test.exs
- test/plugins/set_plugins_command_test.exs
- test/rabbitmqctl_test.exs
CLI is integrated into rabbit `erlang.mk` build process.
Makefiles now define dependencies for MIX.
Added a new formatter for plugins commands output.
System options moved to the separate `config.ex` module for convenience
> RabbitMQ server/release integration

- test/test_helper.exs
Part of rabbitmq/rabbitmq-common#46
> Switch JSON library to JSX

- lib/rabbitmq/cli/ctl/command_modules.ex
- lib/rabbitmq/cli/ctl/commands/cancel_sync_queue_command.ex
- lib/rabbitmq/cli/ctl/commands/close_connection_command.ex
- lib/rabbitmq/cli/ctl/commands/list_bindings_command.ex
- lib/rabbitmq/cli/ctl/commands/list_channels_command.ex
- lib/rabbitmq/cli/ctl/commands/list_connections_command.ex
- lib/rabbitmq/cli/ctl/commands/list_consumers_command.ex
- lib/rabbitmq/cli/ctl/commands/list_exchanges_command.ex
- lib/rabbitmq/cli/ctl/commands/node_health_check_command.ex
- lib/rabbitmq/cli/ctl/commands/report_command.ex
- lib/rabbitmq/cli/ctl/commands/set_vm_memory_high_watermark_command.ex
- lib/rabbitmq/cli/ctl/commands/sync_queue_command.ex
- lib/rabbitmq/cli/ctl/info_keys.ex
- lib/rabbitmq/cli/ctl/status_print.ex
- lib/rabbitmq/cli/default_output.ex
- lib/rabbitmq/cli/formatters/table.ex
* Fix some code consistency issues, mostly spaces around parenthesis, brackets and operators.
* Write large number with underscores (example: 70_000 instead of 70000)
* Write variable names in snake_case
* Remove trailing white spaces
> Improve code consistency

- lib/rabbitmq/cli/ctl/commands/set_operator_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/set_policy_command.ex
Part of rabbitmq/rabbitmq-server#1030
> Use binaries for policy RPC call

- lib/rabbitmq/cli/ctl/commands/encode_command.ex
- test/encode_command_test.exs
Catching up with rabbitmq/rabbitmq-server#979.
Fixes #118
Should be merged once https://github.com/rabbitmq/rabbitmq-server/pull/1032 and https://github.com/rabbitmq/rabbitmq-common/pull/146 are merged into both stable and master.
> Add encode command

- lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
- lib/rabbitmq/cli/formatters/erlang.ex
- lib/rabbitmq/cli/formatters/inspect.ex
- test/diagnostics/cipher_suites_command_test.exs
> Introduce `rabbitmq-diagnostics cipher_suites [--openssl-format]`

- lib/rabbitmq/cli/default_output.ex
- lib/rabbitmq/cli/formatters/plugins.ex
- lib/rabbitmq/cli/plugins/commands/disable_command.ex
- lib/rabbitmq/cli/plugins/commands/enable_command.ex
- lib/rabbitmq/cli/plugins/commands/set_command.ex
- lib/rabbitmq/cli/plugins/plugins_helpers.ex
- test/list_parameters_command_test.exs
- test/parser_test.exs
- test/plugins/disable_plugins_command_test.exs
- test/plugins/enable_plugins_command_test.exs
- test/plugins/list_plugins_command_test.exs
- test/plugins/set_plugins_command_test.exs
- test/test_helper.exs
> Real time output in enable/disable/set commands

- lib/rabbitmq/cli/diagnostics/commands/maybe_stuck_command.ex
- test/diagnostics/maybe_stuck_command_test.exs
> Introduce `rabbitmq-diagnostics maybe_stuck`

- Makefile
- lib/rabbitmq/cli/ctl/commands/help_command.ex
- test/help_command_test.exs
> Sort commands when printing help

- lib/rabbitmq/cli/diagnostics/commands/erlang_cookie_hash_command.ex
- lib/rabbitmq/cli/formatters/erlang_string.ex
- test/diagnostics/erlang_cookie_hash_command_test.exs
> Erlang cookie hash command

- lib/rabbitmq/cli/ctl/commands/clear_global_parameter_command.ex
- lib/rabbitmq/cli/ctl/commands/list_global_parameters_command.ex
- lib/rabbitmq/cli/ctl/commands/set_global_parameter_command.ex
- test/authenticate_user_command_test.exs
- test/change_password_command_test.exs
- test/clear_global_parameter_command_test.exs
- test/clear_parameter_command_test.exs
- test/clear_password_command_test.exs
- test/list_global_parameters_command_test.exs
- test/list_parameters_command_test.exs
- test/set_global_parameter_command_test.exs
- test/set_parameter_command_test.exs
- test/set_permissions_command_test.exs
- test/set_user_tags_command_test.exs
- test/test_helper.exs
Part of rabbitmq/rabbitmq-mqtt#73
> Add global parameters commands

- lib/rabbitmq/cli/ctl/commands/set_vm_memory_high_watermark_command.ex
- test/set_vm_memory_high_watermark_command_test.exs
> Detailed error message in memory threshold validation

- Makefile
- lib/rabbitmq/cli/core/distribution.ex
- lib/rabbitmq/cli/ctl/commands/help_command.ex
- lib/rabbitmq/cli/ctl/commands/join_cluster_command.ex
- lib/rabbitmq/cli/default_output.ex
- lib/rabbitmqctl.ex
- test/set_policy_command_test.exs
- test/set_vm_memory_high_watermark_command_test.exs
Part of https://github.com/rabbitmq/rabbitmq-server/issues/1058
> Getting rid of rabbit_control_main

- lib/rabbitmq/cli/ctl/commands/clear_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/list_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/list_user_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/set_topic_permissions_command.ex
- test/clear_topic_permissions_command_test.exs
- test/list_topic_permissions_command_test.exs
- test/list_user_topic_permissions_command_test.exs
- test/set_topic_permissions_command_test.exs
- test/test_helper.exs
Part of rabbitmq/rabbitmq-server#505
> Topic-based authorisation for publishes

- lib/rabbitmq/cli/ctl/commands/list_vhost_limits_command.ex
- test/clear_vhost_limits_command_test.exs
- test/list_vhost_limits_command_test.exs
- test/set_vhost_limits_command_test.exs
- test/test_helper.exs
Fixes #165 
Requires rabbitmq/rabbitmq-server#1083
> List vhost limits command

- lib/rabbitmq/cli/core/helpers.ex
- lib/rabbitmq/cli/ctl/commands/add_user_command.ex
- lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
- lib/rabbitmq/cli/ctl/commands/change_password_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_global_parameter_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_operator_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_parameter_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_password_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_vhost_limits_command.ex
- lib/rabbitmq/cli/ctl/commands/delete_user_command.ex
- lib/rabbitmq/cli/ctl/commands/delete_vhost_command.ex
- lib/rabbitmq/cli/ctl/commands/set_cluster_name_command.ex
- lib/rabbitmq/cli/ctl/commands/set_global_parameter_command.ex
- lib/rabbitmq/cli/ctl/commands/set_operator_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/set_parameter_command.ex
- lib/rabbitmq/cli/ctl/commands/set_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/set_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/set_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/set_user_tags_command.ex
- lib/rabbitmq/cli/ctl/commands/set_vhost_limits_command.ex
- test/test_helper.exs
Part of https://github.com/rabbitmq/rabbitmq-event-exchange/issues/10
> Provide cli user as user who performs action for event notifications

- lib/rabbitmq/cli/ctl/commands/add_user_command.ex
- test/add_user_command_test.exs
> Format user_already_exists error

- Makefile
... to the directory specified with `$(PREFIX)`.
By default, the source directory is copied using pax(1) so hardlinks are preserved. One can set `USE_SYMLINKS_IN_ESCRIPTS_DIR` to anything to use symlinks instead of hardlinks.
**v2**: The `Makefile` now distinguishes real escripts from linked escripts. So instead of using pax(1) in the new `install` target, real escripts are copied and linked escripts are recreated.
[#138925175]
> Makefile: New `install` target to copy escripts

- lib/rabbitmq/cli/formatters/plugins.ex
- lib/rabbitmq/cli/plugins/plugins_helpers.ex
This ensures that the plugin set is output when enabling/disabling plugins
in offline mode.
Fixes #191
[#146384227]
> Add enabled/disabled plugins to cli output.

- lib/rabbitmq/cli/ctl/rpc_stream.ex
> Avoid streaming if no nodes are available

- lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
Part of https://github.com/rabbitmq/rabbitmq-management/issues/446
> Report vhost status on list_vhosts command

- lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
Related to rabbitmq/rabbitmq-management#460
Requires https://github.com/rabbitmq/rabbitmq-server/pull/1318
> Change state in vhost info to cluster_state

- lib/rabbitmq/cli/core/exit_codes.ex
- lib/rabbitmq/cli/ctl/commands/list_queues_command.ex
- lib/rabbitmq/cli/ctl/rpc_stream.ex
- lib/rabbitmqctl.ex
- test/list_queues_command_test.exs
> Set a timeout on list_queues and a warning if unresponsive ones are found

- Makefile
> Add rabbit module to TEST_DEPS

- Makefile
- mix.exs
- rabbitmq-components.mk
References rabbitmq/rabbitmq-server-release#61.
> Revamp how we manage dependencies 

- lib/rabbitmq/cli/core/config.ex
- lib/rabbitmq/cli/ctl/commands/set_parameter_command.ex
- test/hipe_compile_command_test.exs
- test/list_parameters_command_test.exs
- test/list_vhost_limits_command_test.exs
- test/set_parameter_command_test.exs
Fixes #232 
I reviewed how `Map.merge` is used.
> Fix SetParameterCommand's vhost handling

- mix.exs
> Merge #238 to master

- mix.exs
Reverts rabbitmq/rabbitmq-cli#239. See https://github.com/rabbitmq/rabbitmq-server/pull/1488 for reasoning.
> Revert "Merge #238 to master"

- lib/rabbitmq/cli/formatters/plugins.ex
- lib/rabbitmq/cli/plugins/commands/set_command.ex
> Merge rabbitmq-cli-241 to master

- lib/rabbitmq/cli/formatters/plugins.ex
- lib/rabbitmq/cli/plugins/commands/set_command.ex
> Add function clause for set: case

- lib/rabbitmq/cli/ctl/commands/help_command.ex
- lib/rabbitmq/cli/ctl/commands/set_operator_policy_command.ex
- lib/rabbitmq/cli/ctl/commands/set_policy_command.ex
> Whitespace changes

- lib/rabbitmq/cli/ctl/commands/ping_command.ex
- test/ping_command_test.exs
See #253 for background.
[#158291890]
> Introduce `rabbitmqctl ping`

- lib/rabbitmq/cli/ctl/commands/report_command.ex
Follow-up to #256 
@Ayanda-D FYI!
> Add global parameters to rabbitmqctl report

- test/add_vhost_command_test.exs
Part of rabbitmq/rabbitmq-cli#260
[#160792770]
> Expect rabbitmqctl add_vhost to be idempotent

- Makefile
- README.md
- lib/rabbitmq/cli/ctl/commands/quorum_status_command.ex
- lib/rabbitmq/cli/plugins/commands/list_command.ex
- lib/rabbitmq/cli/queues/commands/add_member.ex
- lib/rabbitmq/cli/queues/commands/delete_member.ex
- mix.exs
See: https://github.com/rabbitmq/rabbitmq-server/pull/1706
Includes a new cli tool with commands to manually adjust quorum queue membership.
> Quorum queue

- lib/rabbitmq/cli/ctl/commands/stop_command.ex
- test/stop_command_test.exs
> Make stop idempotent using --idempotent flag

- lib/rabbitmq/cli/ctl/commands/set_log_level_command.ex
- test/add_vhost_command_test.exs
- test/set_log_level_command_test.exs
> Add command to set log level

- lib/rabbitmq/cli/ctl/commands/list_consumers_command.ex
- test/list_consumers_command_test.exs
[#163089472]
References rabbitmq/rabbitmq-management#649
> Add single active field to list_consumers command

- lib/rabbit_common/records.ex
- lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
- lib/rabbitmq/cli/ctl/commands/list_feature_flags_command.ex
- lib/rabbitmq/cli/formatters/pretty_table.ex
- test/enable_feature_flag_test.exs
- test/list_feature_flags_command_test.exs
- test/test_helper.exs
See rabbitmq/rabbitmq-server#1818 for a description of this change.
> Feature flags support + make #amqqueue{} private

- lib/rabbitmq/cli/ctl/commands/cancel_sync_queue_command.ex
- lib/rabbitmq/cli/ctl/commands/help_command.ex
- lib/rabbitmq/cli/ctl/commands/sync_queue_command.ex
- lib/rabbitmq/cli/queues/commands/add_member_command.ex
- lib/rabbitmq/cli/queues/commands/delete_member_command.ex
- lib/rabbitmq/cli/queues/commands/grow_command.ex
- lib/rabbitmq/cli/queues/commands/shrink_command.ex
> Add descriptions to rabbitmq-queues commands

- lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
Fixes #323.
To reproduce:
* Form a cluster of 2 or more nodes
* Try to remove a node where the `rabbit` app is still running with `rabbitmqctl forget_cluster_node -n rabbit@host-a rabbit@host-b` or similar
* Observe a sensible error with a hint as to what the operator should do
> ctl forget_cluster_node: improve error formatting

- lib/rabbitmq/cli/ctl/commands/list_queues_command.ex
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/1918
[#163984879]
> Add queue type to list queues command

- lib/rabbitmq/cli/ctl/rpc_stream.ex
- lib/rabbitmq/cli/default_output.ex
- test/core/rpc_stream_test.exs
- test/ctl/list_bindings_command_test.exs
- test/ctl/list_channels_command_test.exs
- test/ctl/list_connections_command_test.exs
- test/ctl/list_consumers_command_test.exs
- test/ctl/list_exchanges_command_test.exs
- test/ctl/list_queues_command_test.exs
> Ensure enumerable value is returned from RpcStream

- lib/rabbitmq/cli/core/feature_flags.ex
- lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
> Include feature flag status in cluster status

- lib/rabbitmq/cli/diagnostics/commands/erlang_version_command.ex
- test/diagnostics/erlang_version_command_test.exs
> diagnostics erlang_version: support --offline

- lib/rabbitmq/cli/core/distribution.ex
- lib/rabbitmq/cli/core/helpers.ex
- lib/rabbitmq/cli/core/node_name.ex
- lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
- lib/rabbitmqctl.ex
- test/core/node_name_test.exs
> Improve error reporting for invalid node names

- lib/rabbitmq/cli/ctl/commands/quorum_status_command.ex
requires: https://github.com/rabbitmq/rabbitmq-server/pull/2014
> Switch to pretty table formatter

- lib/rabbitmq/cli/diagnostics/commands/check_alarms_command.ex
- lib/rabbitmq/cli/diagnostics/commands/check_port_listener_command.ex
- lib/rabbitmq/cli/diagnostics/commands/check_virtual_hosts.ex
- lib/rabbitmq/cli/diagnostics/commands/check_virtual_hosts_command.ex
- lib/rabbitmqctl.ex
- test/diagnostics/check_alarms_command_test.exs
- test/diagnostics/check_port_listener_command_test.exs
- test/diagnostics/check_virtual_hosts_command_test.exs
Part of https://github.com/rabbitmq/rabbitmq-cli/issues/302
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2018
> Health check command for virtual hosts

- lib/rabbitmq/cli/queues/commands/add_member_command.ex
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2053
> Provide timeout to add_member command

- lib/rabbitmq/cli/core/config.ex
- lib/rabbitmq/cli/core/paths.ex
- lib/rabbitmq/cli/core/validators.ex
- lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
- lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
- lib/rabbitmq/cli/ctl/commands/list_feature_flags_command.ex
- lib/rabbitmq/cli/ctl/commands/rename_cluster_node_command.ex
- lib/rabbitmq/cli/formatters/pretty_table.ex
- test/ctl/forget_cluster_node_command_test.exs
- test/enable_feature_flag_test.exs
- test/list_feature_flags_command_test.exs
- test/test_helper.exs
References rabbitmq/rabbitmq-server#2028.
Depends on rabbitmq/rabbitmq-common#327.
Depends on rabbitmq/rabbitmq-server#2029.
> Backport feature flags subsystem CLI commands

- lib/rabbitmq/cli/core/config.ex
- lib/rabbitmq/cli/core/input.ex
- lib/rabbitmq/cli/ctl/commands/add_user_command.ex
- lib/rabbitmq/cli/ctl/commands/authenticate_user_command.ex
- lib/rabbitmq/cli/ctl/commands/change_password_command.ex
- lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
- test/ctl/add_user_command_test.exs
- test/ctl/authenticate_user_command_test.exs
- test/ctl/change_password_command_test.exs
- test/rabbitmqctl_test.exs
> ctl: [optionally] accept passwords via stdin

- lib/rabbitmq/cli/ctl/commands/status_command.ex
- test/ctl/set_vm_memory_high_watermark_command_test.exs
- test/ctl/wait_command_test.exs
> diagnostics status: require rabbit app to be running on target node

- lib/rabbitmq/cli/core/listeners.ex
Provide detailed description for prometheus port - instead of default HTTP
> List Prometheus port

- lib/rabbitmq/cli/ctl/commands/add_vhost_command.ex
- lib/rabbitmq/cli/ctl/commands/list_vhosts_command.ex
- lib/rabbitmq/cli/ctl/commands/report_command.ex
- test/ctl/add_vhost_command_test.exs
Part of https://github.com/rabbitmq/rabbitmq-server/issues/2012
> Use new 'description' and 'tag' items on list vhosts

- lib/rabbitmq/cli/queues/commands/rebalance_command.ex
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2098
If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.
> Rebalance quorum queues command

- lib/rabbitmq/cli/queues/commands/rebalance_command.ex
> Use pretty table formatter

- Makefile
- README.md
- lib/rabbitmq/cli/core/doc_guide.ex
- lib/rabbitmq/cli/upgrade/commands/post_upgrade_command.ex
- mix.exs
- test/upgrade/post_upgrade_command_test.exs
Performs the rebalance of all queues after an upgrade. In the future, other operations could be run from this command.
> Post upgrade command

- lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
- lib/rabbitmq/cli/ctl/commands/help_command.ex
- lib/rabbitmq/cli/ctl/commands/status_command.ex
- lib/rabbitmq/cli/diagnostics/commands/check_virtual_hosts_command.ex
- lib/rabbitmq/cli/diagnostics/commands/listeners_command.ex
- lib/rabbitmq/cli/diagnostics/commands/memory_breakdown_command.ex
> Add erlang formatter function heads

- lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex
Add the inet6 family test. When RabbitMQ is listening in ipv6 the test
fails. This commit tests both ipv4 and ipv6.
Enviroment:
```
sudo lsof -i -P -n | grep LISTEN | grep 5672
beam.smp   4833 gabriele   77u  IPv4 49160038      0t0  TCP *:25672 (LISTEN)
beam.smp   4833 gabriele   90u  IPv6 49158841      0t0  TCP [::1]:5672 (LISTEN)
```
bug:
```
$ scripts/rabbitmq-diagnostics check_port_connectivity
Testing TCP connections to all active listeners on node rabbit@leap ...
Error:
Connection to ports of the following listeners on node rabbit@leap failed:
Interface: [::1], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
```
with the fix:
```
$ scripts/rabbitmq-diagnostics check_port_connectivity
Testing TCP connections to all active listeners on node rabbit@leap ...
Successfully …
```
> Add call for IPv6 listening in check_port_connectivity

- lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
- lib/rabbitmq/cli/ctl/commands/status_command.ex
Depends on rabbitmq/rabbitmq-server#2326.
> Improve the display of product name & version (if any)

- lib/rabbitmq/cli/ctl/commands/report_command.ex
- lib/rabbitmq/cli/diagnostics/commands/os_env_command.ex
This includes `rabbitmq-diagnostics os_env` output into `rabbitmq-diagnostics report`
> Include 'rabbitmq-diagnostics os_env' output into 'rabbitmq-diagnostics report'

- test/diagnostics/os_env_command_test.exs
> Don't depend on a single env variable in this test

- test/diagnostics/os_env_command_test.exs
> Handle variable case in this test

- lib/rabbitmq/cli/ctl/commands/decode_command.ex
- lib/rabbitmq/cli/ctl/commands/encode_command.ex
- test/ctl/decode_command_test.exs
- test/ctl/encode_command_test.exs
Part of rabbitmq/credentials-obfuscation#5
> Update for version 2 of credentials-obfuscation

- lib/rabbitmq/cli/ctl/commands/add_user_command.ex
- lib/rabbitmq/cli/ctl/commands/change_password_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/clear_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/delete_user_command.ex
- lib/rabbitmq/cli/ctl/commands/set_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/set_topic_permissions_command.ex
- lib/rabbitmq/cli/ctl/commands/set_user_tags_command.ex
- test/ctl/set_permissions_command_test.exs
Part of rabbitmq/rabbitmq-server#2363.
> Improves error reporting for user and permission-related commands

- README.md
- lib/rabbitmq/cli/core/config.ex
- lib/rabbitmq/cli/core/data_coercion.ex
- lib/rabbitmq/cli/core/listeners.ex
- lib/rabbitmq/cli/core/networking.ex
- lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex
- lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
- lib/rabbitmq/cli/ctl/commands/rename_cluster_node_command.ex
- lib/rabbitmq/cli/ctl/info_keys.ex
- lib/rabbitmq/cli/plugins/plugins_helpers.ex
- lib/rabbitmq/cli/queues/commands/add_member_command.ex
- lib/rabbitmq/cli/queues/commands/delete_member_command.ex
- lib/rabbitmq/cli/queues/commands/grow_command.ex
- lib/rabbitmq/cli/queues/commands/shrink_command.ex
It has been annoying me for a while :)
> Rename Rabbitmq.Atom.Coerce to RabbitMQ.CLI.Core.DataCoercion

- lib/rabbitmq/cli/queues/commands/check_if_node_is_quorum_critical_command.ex
References rabbitmq/rabbitmq-cli#432
> Special case single node clusters for 'rabbitmq-queues check_if_node_is_quorum_critical'

- lib/rabbitmq/cli/ctl/commands/clear_user_limits_command.ex
- lib/rabbitmq/cli/ctl/commands/list_user_limits_command.ex
- lib/rabbitmq/cli/ctl/commands/set_user_limits_command.ex
- test/ctl/clear_user_limits_command_test.exs
- test/ctl/list_user_limits_command_test.exs
- test/ctl/set_user_limits_command_test.exs
- test/test_helper.exs
The following is an implementation of setting/clearing channel limits
for a specific user.
```
rabbitmqctl set_user_limits username '{"max-connections": 50, "max-channels": 500}'
rabbitmqctl set_user_limits username '{"max-connections": 50}'
rabbitmqctl set_user_limits username '{"max-channels": 500}'
```
```
rabbitmqctl set_user_limits username '{"max-connections": 0}'
rabbitmqctl set_user_limits username '{"max-channels": 0}'
```
```
rabbitmqctl set_user_limits username '{"max-connections": -1}'
rabbitmqctl set_user_limits username '{"max-channels": -1}'
```
```
rabbitmqctl clear_user_limits username 'max-connections'
rabbitmqctl clear_user_limits username 'max-channels'
```
```
rabbitmqctl clear_user_limits username 'all'
```
Part of: …
> Per user connection and channel limits CLI

- lib/rabbitmq/cli/core/merges_default_virtual_host.ex
- lib/rabbitmq/cli/queues/commands/reclaim_quorum_memory_command.ex
- test/queues/reclaim_quorum_memory_command_test.exs
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2448
> Reclaim quorum memory command

- lib/rabbitmq/cli/queues/commands/peek_command.ex
- test/ctl/list_user_limits_command_test.exs
- test/diagnostics/erlang_cookie_sources_command_test.exs
- test/queues/peek_command_test.exs
Requires: https://github.com/rabbitmq/rabbitmq-server/pull/2447
> Quorum queue peek command

- lib/rabbitmq/cli/ctl/commands/forget_cluster_node_command.ex
When the node is offline we can only offer a warning - the operator
must use the shrink command once the node is restarted
Fixes https://github.com/rabbitmq/rabbitmq-server/issues/2414
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2453
> Shrink quorum queues on forget cluster node command

- .travis.yml
- .travis.yml.patch
- lib/rabbitmq/cli/core/config.ex
- test/ctl/force_boot_command_test.exs
- test/ctl/forget_cluster_node_command_test.exs
- test/ctl/rename_cluster_node_command_test.exs
If the value for `mnesia_dir` or `feature_flags_file` comes back `undefined` we need to try again in offline mode.
#457
> Handle offline remote node in rename_cluster_node

- lib/rabbitmq/cli/queues/commands/check_if_node_is_quorum_critical_command.ex
they should have transferred their QQ replicas to its peers
and won't be considered for new replica placement
or Raft leader elections.
Closes rabbitmq/rabbitmq-server#2469.
> Don't consider nodes in maintenance mode to be queue quorum critical
