rabbitmq/rabbitmq-cli

Makefile
lib/rabbitmq/cli/formatters/csv.ex
lib/rabbitmq/cli/formatters/formatter_helpers.ex
lib/rabbitmq/cli/formatters/table.ex
mix.exs
test/set_user_tags_command_test.exs

Fixes #115
Flattens `list_consumers`, outputs map keys as a first row. Info items are formatted the same way as with table formatter.

CSV formatter

---

.gitignore
Makefile

When adding a command to a rabbitmq plugin, the build process requires `Elixir.RabbitMQ.CLI.CommandBehaviour` module to be available in `ERL_LIBS`.
To be included in `ERL_LIBS`, rabbitmqctl bytecode files should be located in `ebin` directory.

Copy CTL modules to /ebin to be included in ERL_LIBS

---

Makefile
lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex
lib/rabbitmqctl.ex
mix.exs
test/command_modules_test.exs
test/parser_test.exs
test/test_helper.exs

Fixes #129 
Change the command parsing behaviour to return a command if it was found, or `:no_command` if it wasn't.
Move responsibility for command discovery from `rabbitmqctl` to `parser`

Load command specific options from a single command

---

lib/rabbitmq/cli/core/distribution.ex

Re-implement https://github.com/rabbitmq/rabbitmq-server/issues/890
CLI tools fail in longnames-mode if erlang is not able to determine host
FQDN (with at least one dot in it). E.g. this happens on docker.
And it was not possible to alleviate this situation using any options
from http://erlang.org/doc/apps/erts/inet_cfg.html

Fix longname-mode on hosts without detectable FQDN

---

lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmqctl.ex

Otherwise broken or misconfigured distribution is reported as an
unavailable broker node.

Handle errors from distribution start attempts

---

lib/rabbitmq/cli/core/distribution.ex
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmqctl.ex
mix.exs
test/parser_test.exs

Fixes #135 
If command name is not found, finds a command with Levenshtein distance less or equal to 5 and show a suggestion message.

Suggest similar commands

---

lib/rabbitmq/cli/plugins/commands/disable_command.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
lib/rabbitmq/cli/plugins/commands/list_command.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex

As the new flag suggests, it allows to enable or disable all plugins at once.
This is at least useful to simplify `mk/rabbitmq-run.mk` in rabbitmq-common.
[#136769947]

rabbitmq-plugins: Support enable/disable --all

---

lib/rabbitmq/cli/ctl/commands/close_all_connections_command.ex
test/close_all_connections_command_test.exs
test/test_helper.exs

Closes #155 with https://github.com/rabbitmq/rabbitmq-server/pull/1074
@michaelklishin  I'm not sure that the semantics of how to pair valid options are clear (vhost & limit, node & global, delay with any), any suggestions?
```close_all_connections [-p <vhost> --limit <limit>] [-n <node> --global] [--per-connection-delay <delay>] <explanation>```

Close all connections command

---

Makefile
mix.exs

First, run mix(1) once from the Makefile. We use an mix alias to call all actual mix commands in a single run. Now `make app` takes care of calling the equivalent of `deps.get`, `deps.compile`, `compile` and
`escript.build`. It doesn't match the expected Erlang.mk behavior but it saves us from starting mix(1) multiple times.
Second, only build Erlang dependencies (rabbit_common and amqp_client) once from the Makefile (through Erlang.mk dependency mechanism). In `mix.exs`, their compile command is set to `true` because they are already up-to-date. This saves two no-op builds of those dependencies.
On my laptop, this reduces the no-op build from 10 seconds to 5 seconds.

Makefile, mix.exs: Reduce build time

---

DESIGN.md
lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/ctl/commands/eval_command.ex
test/eval_command_test.exs
test/parser_test.exs

Fixes #10 
Aliases will be loaded from the alias file.
Alias file format
```
alias = command [options]
```
See DESIGN.md for more information.
Extended `eval` command to accept positional arguments. They will be bound to: `_1`, `_2` ...
Named options like vhost will be bound to named variables `_vhost`, `_node` ...

Support command aliases

---

lib/rabbitmq/cli/core/command_modules.ex
lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/ctl/commands/hipe_compile_command.ex
lib/rabbitmq/cli/ctl/validators.ex
lib/rabbitmq/cli/plugins/commands/disable_command.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
lib/rabbitmq/cli/plugins/commands/list_command.ex
lib/rabbitmq/cli/plugins/commands/set_command.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex
mix.exs
test/core/helpers_test.exs
test/hipe_compile_command_test.exs

Originally introduced in https://github.com/rabbitmq/rabbitmq-server/pull/808.
Fixes #178.

Implement `rabbitmqctl hipe_compile`

---

DESIGN.md
lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/core/distribution.ex
lib/rabbitmq/cli/core/parser.ex
test/distribution_test.exs
test/rabbitmqctl_test.exs

Fixes #180 
Add new flag `--erlang-cookie` and environment variable `RABBITMQ_ERLANG_COOKIE`
to configure a cookie for CLI to connect to RabbitMQ node.

Make it possible to specify erlang cookie from command line

---

lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/ctl/commands/set_disk_free_limit_command.ex
lib/rabbitmq/cli/ctl/commands/shutdown_command.ex
lib/rabbitmq/cli/ctl/commands/stop_command.ex
lib/rabbitmq/cli/default_output.ex
lib/rabbitmq/cli/formatters/erlang_string.ex
lib/rabbitmqctl.ex
test/shutdown_command_test.exs

Fixes #181 
Implemented `shutdown` command.
Fixed help message for `stop` command.
Added stream helpers.
`erlang_string` formatter now prints streams of lines without formatting.

Implement the shutdown command (recently introduced in 3.6.x)

---

lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/ctl/commands/wait_command.ex
test/report_command_test.exs
test/test_helper.exs
test/wait_command_test.exs

Make wait command work in stages with timeouts.
- First wait for a pid file to appear (times out)
- Then wait for erlang distribution to start on the node (times out)
- Then wait for application to be running in the node (does not time out)
Default timeout is set to 10 seconds, which should be enough to
write a pid file and start distribution.

Wait in stages.

---

lib/rabbitmq/cli/ctl/commands/set_permissions_command.ex
lib/rabbitmq/cli/ctl/commands/set_topic_permissions_command.ex
lib/rabbitmq/cli/ctl/commands/set_user_tags_command.ex

Most commands use <username> in the help description

Rename <user> to <username> to standarise all rabbitmqctl commands

---

lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex

Ensures the error is returned and not used later on.
Fixes #193

Check `rabbit_mnesia:status` return value

---

lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmq/cli/default_output.ex
lib/rabbitmqctl.ex
test/set_permissions_command_test.exs

Most commands do rpc's only to the target node, but join_cluster
triggers an rpc between nodes. If the rpc to the remote down returns
down/timeout, we must use that value to run the diagnostics.
Using the node from command options in diagnostics will report as down
the wrong node.
Closes #197

Use the output of multirpc to report the down or timed out nodes

---

lib/rabbitmq/cli/ctl/commands/cluster_status_command.ex

If the error is ignored, an Enum exception is triggered which is not
meaningful for the final user. Notifying that something is wrong accessing
to Mnesia files provides a hint. Can be eventually reproduced while
the node is restarting.
Fixes #199

Handle error in `rabbit_mnesia:cluster_nodes/1` on cluster_status command

---

lib/rabbitmq/cli/diagnostics/commands/memory_breakdown_command.ex
lib/rabbitmq/cli/information_unit.ex
lib/rabbitmqctl.ex
test/cancel_sync_command_test.exs
test/diagnostics/memory_breakdown_command_test.exs
test/information_unit.exs
test/set_vm_memory_high_watermark_command_test.exs

Similar to what management UI has had for a while. Here are some output examples:
```
./escript/rabbitmq-diagnostics memory_breakdown
Reporting memory breakdown on node rabbit@mercurio...
code: 0.0265 gb (27.59%)
other_proc: 0.0243 gb (25.3%)
other_system: 0.0187 gb (19.52%)
queue_procs: 0.0118 gb (12.31%)
binary: 0.0093 gb (9.75%)
other_ets: 0.0028 gb (2.89%)
atom: 0.001 gb (1.09%)
connection_channels: 0.0004 gb (0.47%)
connection_writers: 0.0003 gb (0.36%)
metrics: 0.0002 gb (0.21%)
connection_other: 0.0002 gb (0.2%)
connection_readers: 0.0001 gb (0.1%)
mnesia: 0.0001 gb (0.09%)
plugins: 0.0001 gb (0.08%)
msg_index: 0.0 gb (0.03%)
queue_slave_procs: 0.0 gb (0.0%)
mgmt_db: 0.0 gb (0.0%)
```
```
./escript/rabbitmq-diagnostics memory_breakdown --unit "mb"
Reporting memory breakdown on node …
```

Introduce a memory breakdown command

---

lib/rabbitmqctl.ex

Namely JSON and CSV.
Fixes #205.

Supress banner for machine readable formats

---

lib/rabbitmq/cli/core/command_modules.ex
lib/rabbitmq/cli/core/os_pid.ex

Because the regex engine may change between OTP versions it is necessary
to recompile any compiled regexes at runtime in case the engine is not
compatible.
Fixes #208 
[#149227527]

Recompile regexes at runtime.

---

config/config.exs
lib/rabbitmq/cli/core/command_modules.ex

Some distributions set no permissions to read the enabled plugins
file location. This can cause a crash when running not as root or
rabbitmq user.
It was decided that plugins commands can be skipped when printing
the help message if the user have no access to the enabled plugins
file.
The warning message will be displayed in that case.
Addresses https://github.com/rabbitmq/rabbitmq-server/issues/1296

Do not crash command loading if unable to read enabled plugins file.

---

lib/rabbitmq/cli/ctl/commands/restart_vhost_command.ex
lib/rabbitmq/cli/default_output.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
test/decode_command_test.exs
test/list_vhost_limits_command_test.exs
test/restart_vhost_command_test.exs

The command will attempt to restart a vhost.
If restarted successfully, return exit code 0
If the vhost is already started, return exit code 0 and notify that it's already started.
If there is an error restarting, return exit code 70 and the error
Part of rabbitmq/rabbitmq-server#1321
[#149484305]

The command to restart a vhost.

---

lib/rabbitmq/cli/ctl/commands/list_unresponsive_queues_command.ex

This command will wait for every single queue to answer within `<queue-timeout>` milliseconds. If no answer is given, will query the next one. This could potentially be done in parallel, but we risk spawning thousands of processes in some environments. Shall we still do it? 
Part of #207

Command to report unresponsive queues

---

lib/rabbitmq/cli/plugins/commands/list_command.ex

This extra validation wasn't intentional and turns out to be inconvenient
for provisioning and automation projects such as BOSH releases and Docker images.
An easy way to test this is by building the CLI and the server first:
* `cd umbrella/deps/rabbitmq_cli; gmake`
* `cd umbrella/deps/rabbit; gmake`
then running `scripts/rabbitmq-plugins` from `umbrella/rabbit` while providing it a plugins directory to use,
e.g. one from [a 3.7.0 milestone release](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0-beta.19):
```
RABBITMQ_PLUGINS_DIR=~/Tools/rabbitmq/3.7.0.M19/plugins ./scripts/rabbitmq-plugins list
Configured: E = explicitly enabled; e = implicitly enabled
| Status: [failed to contact rabbit@mercurio - status not shown]
|/
[  ] rabbitmq_amqp1_0                  3.7.0-beta.19 …
```

Don't require RabbitMQ node to be running for `rabbitmq-plugins list'

---

Makefile
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/core/validators.ex
lib/rabbitmq/cli/plugins/commands/disable_command.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
lib/rabbitmq/cli/plugins/commands/set_command.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex
lib/rabbitmqctl.ex
test/plugins/disable_plugins_command_test.exs
test/plugins/enable_plugins_command_test.exs
test/plugins/set_plugins_command_test.exs

If flag is set to `--online` the commands should fail if node is not
running.
If flag is not set, they should fallback to offline mode if the
node is not running.
This corresponds to the rabbitmq-plugins.8 manpage.
Made validation aware of online flag.
Define best_effort mode to fallback if node is not running.
Requires rabbitmq/rabbitmq-server#1433
Fixes #226
[#153184802]

Fix rabbitmq-plugins enable/disable/set behavior for --online flag.

---

lib/rabbitmq/cli/diagnostics/commands/memory_breakdown_command.ex

Specifically to https://github.com/rabbitmq/rabbitmq-server/pull/1404.
Closes #228.
[#153217000]

Adapt rabbitmq-diagnostics memory_breakdown to server master

---

README.md
lib/rabbitmq/cli/command_behaviour.ex
lib/rabbitmq/cli/ctl/commands/decode_command.ex
lib/rabbitmq/cli/ctl/commands/encode_command.ex
lib/rabbitmq/cli/ctl/commands/exec_command.ex
lib/rabbitmq/cli/ctl/commands/help_command.ex
lib/rabbitmq/cli/ctl/commands/hipe_compile_command.ex
lib/rabbitmq/cli/ctl/commands/list_ciphers_command.ex
lib/rabbitmq/cli/ctl/commands/list_hashes_command.ex
lib/rabbitmq/cli/plugins/commands/disable_command.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
lib/rabbitmq/cli/plugins/commands/set_command.ex
lib/rabbitmqctl.ex
rabbitmq-components.mk

The callback can be used to disable erlang distribution (offline commands)
or to have command-specific node name and distribution parameters.

 Add an optional callback to control erlang distribution.

---

lib/rabbitmq/cli/core/config.ex

If a user happens to set the following in `rabbitmq-env-conf.bat`, it will be matched:
```
set USE_LONGNAME="true"
```
Fixes rabbitmq/rabbitmq-server#1508

Ensure another string case is taken care of

---

lib/rabbitmq/cli/core/parser.ex
test/parser_test.exs

There are existing users (including RabbitMQ core tests) that
use that sequence because it was previously in the docs.
This relaxes command validation so that if a command-specific
flag overrides a global, we accept it as long as their types match.
Per discussion with @hairyhum.

Accept -t/--timeout before command name [again]

---

lib/rabbitmq/cli/core/parser.ex
mix.exs

Elixir 1.6.6 is the first version to support Erlang 21.0. Bumping the minimum to this version eases packaging: packagers don't have to think about Erlang/Elixir combinations which work.
The upper limit is set to 1.8.0 (not included) because 1.7.x should work fine. However, 1.8.0 will probably drop Erlang 19.x support, at which point we should review this version pinning.
[#159500280]

Require Elixir 1.6.6+, adding support for Elixir 1.7.x at the same time

---

lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/plugins/commands/directories_command.ex
test/plugins/directories_command_test.exs
test/plugins/disable_plugins_command_test.exs
test/plugins/list_plugins_command_test.exs

This introduces a new command, `rabbitmq-plugins directories`, which displays plugin directories and enabled plugins file path.
Closes #261.
[#160792758]

New command: rabbitmq-plugins directories

---

lib/rabbitmq/cli/formatters/table.ex
test/table_formatter_test.exs

There were headers in 3.6 CLI which were not implemented when moving
to the new one.
Fixes #264
[#161326468]

Add headers to the table formatter.

---

lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex

This is more useful to the users of the new config format.
References rabbitmq/rabbitmq-server#1712.
[#160792113]

Output cipher suites one by one

---

lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
test/diagnostics/cipher_suites_command_test.exs

And introduce --erlang-format. They are mutually exclusive.
This change is for 3.8.0 only.
Closes #267.
[#161435591]

rabbitmq-diagnostics: make cipher_suites default to --openssl-format

---

lib/rabbitmq/cli/core/distribution.ex

If longnames are in use, this also ensures that the domain (if known) is appended to the CLI node name
CLI node names will be based on RabbitMQ host names
Fixes #270 
* Start RabbitMQ. I used the generic-unix package. `shostakovich.localdomain` is in my `/etc/hosts` file:
```
RABBITMQ_ALLOW_INPUT=true \
RABBITMQ_NODENAME='rabbit@shostakovich.localdomain' \
RABBITMQ_USE_LONGNAME=true ./sbin/rabbitmq-server
```
* Run the following variations while there are queues in the system (I used PerfTest). Note that none of these depend on the wrapper scripts as the escript is executed directly:
```
RABBITMQ_USE_LONGNAME=true ./escript/rabbitmqctl -n rabbit@shostakovich.localdomain list_queues
./escript/rabbitmqctl -n rabbit@shostakovich.localdomain --longnames list_queues
```

Ensure cli name ends with correct hostname

---

lib/rabbitmq/cli/diagnostics/commands/discover_peers_command.ex
lib/rabbitmq/cli/diagnostics/commands/maybe_stuck_command.ex
lib/rabbitmq/cli/diagnostics/commands/memory_breakdown_command.ex
lib/rabbitmq/cli/diagnostics/commands/runtime_thread_stats.ex
lib/rabbitmq/cli/formatters/msacc.ex
test/diagnostics/cipher_suites_command_test.exs
test/diagnostics/runtime_thread_stats_test.exs

Uses Erlang's microstate accounting data to produce
high level thread state/activity breakdown.
Usage:
``` shell
rabbitmq-diagnostics runtime_thread_stats -i 5
```
Per discussion with @gerhard.
Depends on https://github.com/rabbitmq/rabbitmq-common/pull/286.

New diagnostics command: runtime_thread_stats

---

lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmq/cli/plugins/commands/disable_command.ex
lib/rabbitmq/cli/plugins/commands/enable_command.ex
lib/rabbitmq/cli/plugins/commands/set_command.ex
lib/rabbitmq/cli/plugins/error_output.ex
lib/rabbitmqctl.ex
test/plugins/disable_plugins_command_test.exs
test/plugins/enable_plugins_command_test.exs

There are two main types of errors that I see in practice:
* Insufficient enabled plugins file permission (or the file does not exist)
* Enabled plugins file used by CLI tools does not match that of
the target node
So the test scenarios should use `RABBITMQ_ENABLED_PLUGINS_FILE` files:
* Owned by `root` without group/world permissions
* That do not exist
* That are not readable or writable
* That are different from those used by the target node (in online mode)
[#162757498]

Improve error message formatting for rabbitmq-plugins commands

---

lib/rabbitmq/cli/ctl/commands/list_consumers_command.ex

Fixes #284 
Note that the second commit only contains cosmetic changes after running:
```
mix format lib/rabbitmq/cli/ctl/commands/list_consumers_command.ex
```

Fix list_consumers command when querying cluster

---

lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
lib/rabbitmq/cli/diagnostics/commands/runtime_thread_stats.ex
lib/rabbitmq/cli/diagnostics/commands/tls_versions.ex
lib/rabbitmq/cli/formatters/string_per_line.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex
test/diagnostics/tls_versions_command_test.exs
test/test_helper.exs

Like `rabbitmq-diagnostics cipher_suites` but for supported (available in the runtime)
TLS versions.
[#162832991]

New command: rabbitmq-diagnostics tls_versions

---

lib/rabbitmq/cli/diagnostics/commands/is_booting.ex
lib/rabbitmq/cli/diagnostics/commands/is_running.ex
test/diagnostics/is_booting_test.exs
test/diagnostics/is_running_test.exs
test/test_helper.exs

Part one of #292 introduces
* `rabbitmq-diagnostics is_running` which returns a success if the node is fully booted and running (as reported by `rabbit:is_booted/1`). This command can be used as/in a health check and meant to be used both interactively and non-interactively.
*  * `rabbitmq-diagnostics is_booting` which returns a success if the node is currently booting (as reported by `rabbit:is_booting/1`). For full booted (running) and stopped nodes it would report a failure. This command is meant for interactive use only and mostly for completeness/troubleshooting. It is *NOT* a good fit for health checks since it will return a failure the vast majority of the time (unless you are lucky to catch a node booting or booting takes a long time)

Introoduce rabbitmq-diagnostics is_running, is_booting

---

lib/rabbitmq/cli/formatters/json.ex
lib/rabbitmq/cli/plugins/commands/is_enabled.ex
lib/rabbitmq/cli/plugins/plugins_helpers.ex
test/plugins/is_enabled_command_test.exs

Part of #292.
To QA:
1. Start a node from `umbrella/deps/rabbitmq_server_release` the same was as for running the test suite: `gmake run-broker PLUGINS="rabbitmq_federation rabbitmq_stomp"`
2. Switch to `deps/rabbit`, run `gmake`
3.  Try various combinations
``` bash
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_stomp --offline --formatter=json; echo $?;
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_stomp rabbitmq_local --offline; echo $?;
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_stomp rabbitmq_local; echo $?;
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_local; echo $?;
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_stomp --offline; echo $?;
./scripts/rabbitmq-plugins -q is_enabled rabbitmq_stomp rabbitmq_federation --offline; echo $?;
./scripts/rabbitmq-plugins …
```

Introduce rabbitmq-plugins is_enabled [plugin 1] [plugin 2] [...]

---

lib/rabbitmq/cli/core/accepts_one_positional_argument.ex
lib/rabbitmq/cli/core/accepts_one_positive_integer_argument.ex
lib/rabbitmq/cli/ctl/commands/await_online_nodes_command.ex
lib/rabbitmq/cli/diagnostics/commands/check_port_connectivity_command.ex
lib/rabbitmq/cli/diagnostics/commands/check_port_listener_command.ex
lib/rabbitmq/cli/diagnostics/commands/check_protocol_listener_command.ex
lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex
test/close_all_connections_command_test.exs
test/diagnostics/check_port_connectivity_command_test.exs
test/diagnostics/check_port_listener_command_test.exs
test/diagnostics/check_protocol_listener_command_test.exs
test/diagnostics/diagnostics_helpers_test.exs

Part of #292, per discussion with @gerhard.
To QA:
1. Start a node for running the tests
2. `gmake`
3. `for i in 5672 25672 61613 123123 15672; do ./escript/rabbitmq-diagnostics -q check_port_listener $i; echo $?; done`
4. `for i in amqp stomp cli clustering amqp091 amqp1.0 lolz; do ./escript/rabbitmq-diagnostics -q check_protocol_listener $i; echo $?; done`

Introduces listener check commands

---

lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/formatter_behaviour.ex
lib/rabbitmq/cli/formatters/report.ex
lib/rabbitmq/cli/formatters/table.ex
lib/rabbitmqctl.ex

Add new callbacks to formatter_behavior: switches/0 and aliases/0
Merge them with command switches and aliases on parsing.
There is an example switch in the table formatter, enabling header padding.

Make it possible for formatters to define arguments.

---

lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/ctl/commands/await_startup_command.ex
test/ctl/await_startup_command_test.exs
test/ctl/shutdown_command_test.exs

To go with rabbitmq/rabbitmq-server#1848.

New command: `rabbitmqctl await_startup`

---

lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/ctl/commands/help_command.ex
lib/rabbitmqctl.ex
test/rabbitmqctl_test.exs

Add a new default switch `help`
Add an alias `?`
Make rabbitmqctl display command help if this option is true for known commands.

Make it possible to get command help by typing 'rabbitmqctl mycommand --help'

---

lib/rabbitmqctl.ex
test/rabbitmqctl_test.exs

Note that there's a different between the case with no arguments
(exits with EX_USAGE) and --help (exits successfully).
Per discussion with the team.
Closes #307.

Support bare --help

---

lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/core/node_name.ex
lib/rabbitmq/cli/ctl/commands/join_cluster_command.ex
lib/rabbitmq/cli/ctl/commands/update_cluster_nodes_command.ex
lib/rabbitmqctl.ex
test/core/helpers_test.exs
test/ctl/close_all_connections_command_test.exs
test/ctl/close_connection_command_test.exs
test/ctl/start_app_command_test.exs
test/ctl/stop_app_command_test.exs

Fixes #311 
Bug introduced by #279
To reproduce, start two nodes with `RABBITMQ_USE_LONGNAME=true` and long node names, and try to join them into a cluster. You will see the error reported via the mailing list:
```
** (FunctionClauseError) no function clause matching in RabbitMQCtl.format_error/3    
The following arguments were given to RabbitMQCtl.format_error/3:
{:badmatch, {:error, :badarg}}
%{disc: false, longnames: true, node: :"rabbit@tec-19.example.com", ram: false, timeout: :infinity}
RabbitMQ.CLI.Ctl.Commands.JoinClusterCommand
(rabbitmqctl) lib/rabbitmqctl.ex:290: RabbitMQCtl.format_error/3
(rabbitmqctl) lib/rabbitmqctl.ex:76: anonymous fn/5 in RabbitMQCtl.exec_command/2
(rabbitmqctl) lib/rabbitmqctl.ex:36: RabbitMQCtl.main/1
(elixir) lib/kernel/cli.ex:105: anonymous fn/3 in …
```

Ensure longnames option is passed to normalise_node

---

lib/rabbitmq/cli/core/parser.ex
mix.exs

Elixir provides String.jaro_distance function, which is similar to
the levenstain distance.
This allows us to remove a dependency.

Use elixir internal distance function instead of a library for command similarity comparison.

---

lib/rabbitmq/cli/core/node_name.ex
lib/rabbitmq/cli/ctl/commands/shutdown_command.ex
test/ctl/shutdown_command_test.exs

inet_db is not a very reliable source as it doesn't take
node name CLI arguments and ERL_INETRC file settings.
That can lead to false positives in environments where
inet_db returns the same value (e.g. `localhost`) for
every cluster member.
Per discussion with @gerhard.
Closes #327.
References #309.

ctl shutdown: infer hostnames from node names

---

lib/rabbitmq/cli/core/exit_codes.ex
lib/rabbitmq/cli/ctl/commands/enable_feature_flag_command.ex
lib/rabbitmq/cli/ctl/commands/list_feature_flags_command.ex
lib/rabbitmqctl.ex
test/ctl/enable_feature_flag_test.exs

This makes `ctl list_feature_flags` handle missing rabbit_ff_extra modules on target node.
@dumbbell @lukebakken @gerhard  if this is the behavior we want I will extend it to more commands. Alternatively we could return an empty list of feature flags (this may be more operator-friendly during upgrades).
[#163980302]

Feature flag commands: handle missing rabbit_ff_extra modules on target node

---

lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
test/diagnostics/cipher_suites_command_test.exs

Support new map format for cipher suites added in OTP-20.3
Support `--all` flag to get all available ciphers
Addresses #342
Depends on changes in rabbitmq-server https://github.com/rabbitmq/rabbitmq-server/pull/1991

Add a flag to cipher_suites command to get all ciphers. Add --format flag to select format. Remove openssl_format flag

---

lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
test/diagnostics/cipher_suites_command_test.exs

This is a backport of #347.
Default format is erlang and the `--openssl-format` flag is supported
for backwards compatibility.
Addresses #342 for 3.7
Depends on changes in rabbitmq/rabbitmq-server#1992

Add a flag to cipher_suites command to return all available suites. Add format flag to select suite format. 3.7

---

Makefile
lib/rabbitmq/cli/diagnostics/commands/observer_command.ex
mix.exs
test/diagnostics/observer_command_test.exs
test/test_helper.exs

This introduces a new command, `rabbitmq-diagnostics observer`, which provides a way to start [observer CLI](https://github.com/zhongwencool/observer_cli) on the target node.
Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2006.
Per discussion with @gerhard.

Observer CLI integration

---

lib/rabbitmq/cli/core/listeners.ex
lib/rabbitmq/cli/ctl/commands/help_command.ex
lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex

Elixir checks endianness and prints this warning:
```
Elixir is running in a system with a different endianness than the one its source code was compiled in. Please make sure Elixir and all source files were compiled in a machine with the same endianness as the current one: big"
```
on big endian systems.
This warning is mostly there because of precompiled regexp fearure in Elixir.
To make code work on all systems, regexes are now recompiled in runtime.
Another question is: should we remove the warning now when the code may run on any endianness?

WIP Make rabbitmqctl work with any endianness.

---

lib/rabbitmq/cli/ctl/commands/list_queues_command.ex

Type is a new argument for 3.8.x. Listing it here causes rabbitmqctl report to
crash with {nocatch,{bad_argument,type}} when it tries to list queues with all
arguments.

remove unsupported type argument from list queues command

---

lib/rabbitmq/cli/diagnostics/commands/schema_info_command.ex
test/diagnostics/schema_info_command_test.exs

Logs by default name, cookie, active_replicas and user_properties
Any other mnesia property can be requested as info key
Needs https://github.com/rabbitmq/rabbitmq-server/pull/2033
Closes #330 
[#164550205]

Command to log schema information

---

lib/rabbitmq/cli/command_behaviour.ex
lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/core/log_files.ex
lib/rabbitmq/cli/diagnostics/commands/log_location_command.ex
lib/rabbitmq/cli/diagnostics/commands/log_tail_command.ex
lib/rabbitmq/cli/diagnostics/commands/log_tail_stream.ex
lib/rabbitmq/cli/printers/std_io_raw.ex
lib/rabbitmqctl.ex
test/diagnostics/log_location_command_test.exs
test/diagnostics/log_tail_command_test.exs
test/diagnostics/log_tail_stream_command_test.exs
test/test_helper.exs

Added new commands:
- `log_location` - get default log location
- `log_location --all` - get all logs locations
- `log_tail [-N <number>]` - get last N lines from the default log
- `log_tail_stream [-d <duration>]` - stream log messages from the deafault log
Default N is 10, default duration is `:infinity`.
Log streaming does not detect the log file to be deleted (because it's a hard thig to do), but that's similar to `tail -f`.
Added a new printer, which prints to the std_io, but does not split lines. This is because log data may contain partial lines.
Reading last N lines reads a buffer of data from the end of the file and counts lines. If there are not enough lines - the buffer is increased. This works well enough for reasonable number of lines.
Open questions:
- Should duration be …

Diagnostics commands that access server logs

---

lib/rabbitmq/cli/diagnostics/commands/observer_command.ex

It works perfectly fine without it. We are more likely to want to look into the Erlang VM if the rabbit app is not running.
Didn't think it was worth writing a test for this, but I am submitting it as a PR in case you think differently @michaelklishin.

Do not require rabbit app for rabbitmq-diagnostics observer

---

lib/rabbitmq/cli/ctl/commands/set_parameter_command.ex
test/ctl/set_parameter_command_test.exs

There was an inversion between parameter name and component in the `set_parameter` command output. Fixed it.

Fix set_parameter command output

---

lib/rabbitmq/cli/formatters/json_stream.ex
test/core/json_stream_test.ex

Some streaming commands with a duration argument can send the empty
string as the output (along with a finishing marker). This case was not
handled properly and would result in a stack trace when the command
returned once the duration has elapsed.
To reproduce:
```
./rabbitmq-diagnostics consume_event_stream --duration 5
Function clause.
Stacktrace:
(rabbitmqctl) lib/rabbitmqctl.ex:45: RabbitMQCtl.main/1
(elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Handle empty output in JSON stream

---

lib/rabbitmq/cli/core/doc_guide.ex
lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/ctl/commands/change_password_command.ex
lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
lib/rabbitmq/cli/default_output.ex
lib/rabbitmq/cli/diagnostics/commands/cipher_suites_command.ex
lib/rabbitmqctl.ex
test/core/default_output_test.exs
test/ctl/export_definitions_command_test.exs
test/ctl/import_definitions_command_test.exs
test/fixtures/files/definitions.json

This introduces new commands for definition export and import that does not depend on any plugins:
``` bash
rabbitmqctl export_definitions /tmp/definitions.et --format=erlang --silent
rabbitmqctl import_definitions /tmp/definitions.et --format=erlang --silent
```
``` bash
rabbitmqctl export_definitions - --format=json --silent | jq
```
``` bash
./escript/rabbitmqctl export_definitions - --format=json | ./escript/rabbitmqctl import_definitions --format=json
```
``` bash
./escript/rabbitmqctl import_definitions --format=json ./escript/rabbitmqctl import_definitions --format=json ./test/fixtures/files/definitions.json
```
Part of rabbitmq/rabbitmq-management#749 and depends on other PRs mentioned in that issue.
Part of rabbitmq/rabbitmq-management#749.

New commands for definition management

---

lib/rabbitmq/cli/ctl/commands/import_definitions_command.ex
lib/rabbitmqctl.ex

Errors like :badarg, :function_clause, etc indicate a serious error. It would be handy for users to immediately get the stack trace to tell us.

Ensure stack trace is always printed for certain errors

---

lib/rabbit_common/records.ex
lib/rabbitmq/cli/queues/commands/check_if_node_is_quorum_critical_command.ex
lib/rabbitmqctl.ex
test/queues/check_if_node_is_quorum_critical_command_test.exs
test/queues/quorum_status_command_test.exs

Introduce `rabbitmq-queues check_if_node_is_quorum_critical` that returns a non-zero status if shutdown or removal of target node would make one or more quorum queues from sustaining a quorum.
Part one of rabbitmq/rabbitmq-cli#389.

Introduce `rabbitmq-queues check_if_node_is_quorum_critical`

---

lib/rabbitmq/cli/queues/commands/check_if_node_is_mirror_sync_critical_command.ex
test/queues/check_if_node_is_mirror_sync_critical_command_test.exs

This is similar to #391 but introduces a similar command for classic mirrored queues:
```
rabbitmq-queues check_if_node_is_mirror_sync_critical
```
This check would fail if the target node hosts one or more classic mirrored queues (masters) that have no online in sync mirrors.
Part two of #389.

Introduce rabbitmq-queues check_if_node_is_mirror_sync_critical

---

lib/rabbitmq/cli/ctl/commands/status_command.ex

They are printed in addition to the underlying RabbitMQ version.
If it is unavailable, for instance because the node is old enough to not export the product info, we use "RabbitMQ" as the name and the underlying RabbitMQ version as the version.
This patch depends on rabbitmq/rabbitmq-server#2257.

status_command: Show product info

---

lib/rabbitmq/cli/ctl/commands/wait_command.ex

... down from 10% of the configured timeout.
This has a significant impact on the time it takes to start RabbitMQ in all our testsuites. rabbitmq-ct-helpers sets a wait timeout of 180 seconds. Thus before this patch, the wait loop would sleep for 18
seconds between each check. Given it takes about 1.5 seconds to start RabbitMQ, a lot of time is wasted here.
Here are some numbers after running testsuites with and without this patch:
* `make ct-fast` in rabbitmq-server: 8m15s down to 4m58s
* `make ct` in rabbitmq-mqtt: 9m23s down to 6m43s
* `make ct` in rabbitmq-stomp: 4m31s down to 2m04s

wait_command.ex: Change `wait` internal sleep to one second

---

mix.exs

This fixes several compilation warnings and looks like to fix the CLI with the upcoming Erlang 23.0.

mix.exs: Bump `csv` to version 2.3.x

---

lib/rabbitmq/cli/diagnostics/commands/os_env_command.ex
test/diagnostics/os_env_command_test.exs

This introduces a new diagnostics command, `rabbitmq-diagnostics os_env`.
It prints RabbitMQ-specific environment variables that
are set on the target node. Can be used to inspect env variable-based
configuration without access to the target host.

Introduce 'rabbitmq-diagnostics os_env'

---

lib/rabbitmq/cli/ctl/commands/await_startup_command.ex
lib/rabbitmq/cli/upgrade/commands/await_online_quorum_plus_one_command.ex
lib/rabbitmq/cli/upgrade/commands/await_online_synchronized_mirror_command.ex
test/ctl/await_startup_command_test.exs
test/upgrade/await_online_quorum_plus_one_command_test.exs
test/upgrade/await_online_synchronized_mirror_command_test.exs

This addresses a typo in #409 as well as a couple of default timeouts that were specified incorrectly (assumed the values was in seconds instead of milliseconds).
Spotted by @gerhard in #409.

#409 followup

---

lib/rabbitmq/cli/core/config.ex
lib/rabbitmq/cli/core/helpers.ex
lib/rabbitmq/cli/core/node_name.ex
test/core/helpers_test.exs

During the 3.8.4 cycle we have backported `rabbit_env` to v3.8.x.
Instead of messing with env variable prefixing, it tries both
RABBITMQ_{VAR} and {VAR} environment variables. However,
in CLI tools node name currently only picks up RABBITMQ_NODENAME,
so environments where node name has to be explicitly configured
via rabbitmq-env.conf:
``` shell
NODENAME=rabbit@our.custom.hostname
```
would not pick this node name up. RABBITMQ_NODENAME had to be added
as a workaround.
With this change the behavior of CLI tools and the server is closer.
Note that this updates a few places which used `Config.get_option/2`
to get a "default node name" which more often than not ended up
being a node prefix ("rabbit"). Those tests had to be updated
to use `Config.default/1`.
Closes #421.
References …

Rely on rabbit_env to infer node name

---

lib/rabbitmq/cli/ctl/commands/status_command.ex

This exposes Raft data directory in `rabbitmq-diagnostics status`. Part of rabbitmq/rabbitmq-server#2354.

List Raft data directory in status

---

lib/rabbitmq/cli/ctl/commands/node_health_check_command.ex

* It requires a fully booted node, so not generally suitable for a Kubernetes readiness probe.
* It can produce false positives
* It is too intrusive and CPU-intensive to use at scale
* Most operators do not understand what it really does and when they learn about it,
consider it to be too opinionated and intrusive
Time for the One True Health Check™ to retire from duty.
Part of rabbitmq/rabbitmq-cli#426
Per discussion with @lukebakken

Deprecate 'ctl node_health_check'

---

lib/rabbitmq/cli/diagnostics/commands/list_network_interfaces_command.ex
test/diagnostics/list_network_interfaces_command_test.exs

To make it easier to discover them without using `rabbitmqctl eval` and obscure functions.
Closes rabbitmq/rabbitmq-cli#424

Introduce 'rabbitmq-diagnostics list_network_interfaces'

---

lib/rabbit_common/records.ex
lib/rabbitmq/cli/core/networking.ex
lib/rabbitmq/cli/diagnostics/commands/resolve_hostname_command.ex
lib/rabbitmq/cli/diagnostics/commands/resolver_info_command.ex
test/diagnostics/resolve_hostname_command_test.exs
test/diagnostics/resolver_info_command_test.exs

Helps with troubleshooting host name resolution behavior
on nodes and locally for CLI tools.
This is obviously not meant to be a replacement for existing tools such as dig,
only a way to quickly spot obvious irregularities, e.g. those
in environments that use custom [Erlang inetrc files](https://erlang.org/doc/apps/erts/inet_cfg.html).
Per discussion @harshac.

Introduce 'rabbitmq-diagnostics resolve_hostname'

---

lib/rabbitmq/cli/ctl/commands/export_definitions_command.ex
test/ctl/clear_parameter_command_test.exs
test/ctl/export_definitions_command_test.exs
test/ctl/import_definitions_command_test.exs
test/ctl/set_parameter_command_test.exs
test/fixtures/files/definitions.json

otherwise, it would be serialized as a list of pairs, which is
not the format the import path (or an operator) expects.
Closes #435.

rabbitmqctl export_definitions: ensure that parameter values are maps

---

lib/rabbitmq/cli/auto_complete.ex
lib/rabbitmq/cli/core/parser.ex
lib/rabbitmq/cli/ctl/commands/help_command.ex
lib/rabbitmqctl.ex
test/core/auto_complete_test.exs
test/ctl/help_command_test.exs
test/rabbitmqctl_test.exs

* `help` printed an "Error:" at the top for no reason
* `help [command]` with a non-existent command did not offer a suggestion
like an attempt to invoke a non-existent command would
* Exit codes were not consistent
* `help --list-commands` had line break issues
With this change,
* `help` is consistent with --help
* `help [command]` is consistent with `[command] --help`
* If a command is not found, either during the execution flow
or `help [commnad]`, we consistently attempt a Jaro distance suggestion
* Successful or effectively successful exits from the `help` command do not produce any error messages at the top

Make --help, help usage help messages consistent

---

lib/rabbitmq/cli/queues/commands/check_if_node_is_mirror_sync_critical_command.ex

as it would produce a confusing false positive.
Per discussion with @harshac, @ansd.
Closes rabbitmq/rabbitmq-cli#432

if a node is the only cluster member, pass on the mirror sync critical check

---

lib/rabbitmq/cli/core/ansi.ex
lib/rabbitmq/cli/core/distribution.ex

It's not worth the confusion it causes in practice since the server does not support it.
To test:
``` shell
RABBITMQ_ERLANG_COOKIE=$(cat $HOME/.erlang.cookie) ERL_LIBS=../rabbit/plugins ./escript/rabbitmqctl status
RABBITMQ_ERLANG_COOKIE="mismatching-value" ERL_LIBS=../rabbit/plugins ./escript/rabbitmqctl status
ERL_LIBS=../rabbit/plugins ./escript/rabbitmqctl status --erlang-cookie $(cat $HOME/.erlang.cookie)
ERL_LIBS=../rabbit/plugins ./escript/rabbitmqctl status --erlang-cookie mismatching-value
```
Per discussion with @gerhard @dumbbell.
Closes #443.

Deprecate RABBITMQ_ERLANG_COOKIE env variable support

---

lib/rabbitmq/cli/diagnostics/commands/erlang_cookie_sources_command.ex
test/diagnostics/erlang_cookie_sources_command_test.exs

to help troubleshoot authentication issues.
I could not quickly locate an Erlang function that would return the expected path in OTP so
we reinvent what [this BIF does](https://github.com/erlang/otp/blob/master/lib/erl_interface/src/connect/ei_connect.c#L2942) in C to cover the Windows-specific special handling of the `HOMEDRIVE` and `HOMEPATH` env variables.
Example output:
```
Cookie File
Effective user: user
Effective home directory: /Users/user
Cookie file path: /Users/user/.erlang.cookie
Cookie file exists? true
Cookie file type: regular
Cookie file access: read
Cookie file size: 20
Cookie CLI Switch
--erlang-cookie value set? false
--erlang-cookie value length: 0
Env variable  (Deprecated)
RABBITMQ_ERLANG_COOKIE value set? false
RABBITMQ_ERLANG_COOKIE value length: 0
```
Inspired by …

Introduce 'rabbitmq-diagnostics erlang_cookie_sources'

---

lib/rabbitmq/cli/ctl/commands/status_command.ex

Note that with `--formatter=json`, the command already reports that value.
Spotted by Jon P on rabbitmq-users and @lukebakken.

Include total amount of memory used into 'rabbitmq-diagnostics status' output

---

mix.exs

See https://github.com/rabbitmq/rabbitmq-ci/pull/33
Part of an effort to use Elixir 1.9 as the minimum.
cc @dumbbell

Update minimum required Elixir version

---

lib/rabbitmq/cli/core/distribution.ex

This will limit the number of CLI node names to 1024 by taking the
current epoch seconds modulo a random number between 1 and 1024.
Follow-up to the following:
rabbitmq/rabbitmq-server#552
https://groups.google.com/d/msg/rabbitmq-users/aSnlC5hSvMk/sIWtv5fxCgAJ

Limit the set of CLI node names that can be generated to prevent potential atom table exhaustion

---

lib/rabbitmq/cli/ctl/commands/list_queues_command.ex

Depends on https://github.com/rabbitmq/rabbitmq-server/pull/2475, which allows all queue types to return empty values for unknown keys. Without the server changes, the `list_queues` command was broken when requesting type specific keys such as queue slaves.

Add relevant info keys for stream and quorum queues

---

lib/rabbitmq/cli/ctl/commands/add_user_command.ex

to give the user an idea that she would have to
grant permissions to the newly added user.

Provide an extra hint in 'rabbitmqctl add_user' output
